### ISSUE TITLE
Is there a way to run multiple jobs in parallel with one Proxy server running?

### ISSUE THREAD

**Issue by michhyun1** [saucelabs/sauce-connect-action#10]
The issue I'm running into is that I want to run ~7 tests in parallel on one tunnel. I want to be able to start the proxy server (Job 1) in a github actions job and create one tunnel and **keep it running**. Then, my other Job (Job 2) will run the job matrix strategy to run 7 jobs in parallel using the one tunnel identifier that was created (in Job 1) and is running in the previous step. 

The problem is, I can't persist the proxy server. It gets killed as soon as (Job 1) ends and the process is cleaned up before my concurrent jobs (in Job 2) are able to finish. Is there a way to run the proxy server in the background and not get cleaned up before all my tests pass? 

The only other solution I have is that I can setup a proxy server for each test that is created in the job matrix, (that way the proxy server isnt cleaned up before the rest of the job, including the test, is finished) but I dont think having 7+ tunnels is correct. The documentation says there is only 5 tunnels allowed per team.

**Comment by michhyun1** [comment]
I was thinking of setting up a long-standing tunnel manually, and then have all the tests point to that tunnel. I just dont know how well the tunnel will hold up. It says in the docs that its recommended that the tunnel be restarted every 24 hours

**Comment by christian-bromann** [comment]
> The problem is, I can't persist the proxy server. It gets killed as soon as (Job 1) ends and the process is cleaned up before my concurrent jobs (in Job 2) are able to finish. Is there a way to run the proxy server in the background and not get cleaned up before all my tests pass?

I think this is a GH action limitation. Why not run 1 tunnel per job? Even though it adds to the run time of the test but as long as you run them in parallel it might still fit your requirements?

> The documentation says there is only 5 tunnels allowed per team.

Can you send me a link to that documentation? I can check in with the @saucelabs/scdev team.

> I was thinking of setting up a long-standing tunnel manually, and then have all the tests point to that tunnel.

The reason why you would use `sauce-connect-action` is because you have an application that is statically deployed in your GH workflow. Starting a tunnel on a different machine would not help the browser in the VM to connect to that application.

**Comment by michhyun1** [comment]
Link to the documenation: https://wiki.saucelabs.com/display/DOCS/FAQs+for+Sauce+Connect+Proxy+and+Real+Device+Testing

'We are allowing five open tunnels per team. Should you require more please contact your Customer Success Manager.'

**Comment by michhyun1** [comment]
Thanks, I'll try to create a new tunnel for each job.

**Comment by christian-bromann** [comment]
I reached out to the @saucelabs/scdev team and they say this number can be increased. Do you think this issue can be closed or is there anything we can improve in this action?

**Comment by michhyun1** [comment]
It can be closed, thanks for your help!
