### ISSUE TITLE
The container isn't terminated when the action run in self-hosted runner

### ISSUE THREAD

**Issue by KengoTODA** [saucelabs/sauce-connect-action#11]
Hello,

Now I'm trying to use this action in our self-hosted runner (Ubuntu 18.04), and found that this action doesn't terminate the docker instance even after the action run has finished.
I [tried to use `post-entrypoint`](https://github.com/saucelabs/sauce-connect-action/compare/master...KengoTODA:shutdown-sauce-connect) to run `docker stop`, but it failed because the cleanup operation runs in another docker instance then it cannot touch the instance runs `saucelabs/sauce-connect`.

To solve this issue from root, I think we need to migrate this action to [the JavaScript based action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action), and call `docker` command from both [`main`](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#runsmain) and [`post`](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#post) then the operation triggered by `post` can stop the instance by `docker stop`.

I'm not sure why we choose docker-based implementation, so could you tell me how we should solve this issue?
If you're welcome to see PR for this conversion, I will handle it. Thanks in advance!

note: Known workaround is terminate them manually at https://app.saucelabs.com/tunnels

**Comment by christian-bromann** [comment]
Thanks for raising the issue!

> If you're welcome to see PR for this conversion, I will handle it. Thanks in advance!

Yes absolutely, let's have this changed. When I was testing it, it seemed for me that tunnels got shut down properly but I might be wrong.

**Comment by KengoTODA** [comment]
I'm making progress at https://github.com/KengoTODA/sauce-connect-action/runs/1409791763?check_suite_focus=true and `docker stop` fails due to `page not found` error. I will investigate more later.

**Comment by KengoTODA** [comment]
I've created #12 to close this issue, please check it when you have time. 
Thanks in advance! :)
