### ISSUE TITLE
Passing Tunnel ID to tests

### ISSUE THREAD

**Issue by petja-laitila** [saucelabs/sauce-connect-action#18]
I'm trying to get sauce tests run with maven. Problem is I don't seem to figure out how to pass Tunnel ID to the tests. Using  tunnelIdentifier: github-action-tunnel creates tunnel on sauce, but github-action-tunnel is the name of the tunnel and I need to pass tunnel-identifier to my test. 
Something like this:
capabilities.setCapability("tunnel-identifier", getSauceTunnelId());
On travis their sauce add-on created environment variable env.TRAVIS_JOB_NUMBER that we can then pass to the tests.
Any way to do something similar?

**Comment by christian-bromann** [comment]
> and I need to pass tunnel-identifier to my test.

You can do this either through environment variables or hardcoded.
