### ISSUE TITLE
Custom domains not found

### ISSUE THREAD

**Issue by petja-laitila** [saucelabs/sauce-connect-action#19]
I'm starting wildfly container with maven to run application in made up domain which I put in hosts in machine that runs actions.
Sauce can not find that address and responds with "unknown error: net::ERR_NAME_NOT_RESOLVED\n...."
Is this because sc runs on docker container and does not know about this domain? Is there a way around this?

**Comment by waggledans** [comment]
Sauce Connect Proxy Github action runs in docker container and can't resolve an arbitrary made-up domain name. The solution is either add a nameserver that can resolve the domain or run SC locally where you can update `/etc/hosts` file with your domain name resolution.
