### ISSUE TITLE
Error: Unable to resolve action `saucelabs/sauce-connect-action@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by rhansen** [saucelabs/sauce-connect-action#23]
When I try to use this action GitHub gives me an error:

```
Failed to resolve action download info. Error: Unable to resolve action `saucelabs/sauce-connect-action@v1`, unable to find version `v1`
```

For full logs see: https://github.com/ether/etherpad-lite/pull/4833/checks?check_run_id=1944978463

**Comment by rhansen** [comment]
This repository doesn't have a `v1` branch or tag, so it's not surprising that it failed.

The [GitHub docs on action release management](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management) say to create a `v1` tag that you move whenever you release a new v1.x version. That seems weird to me—tags are supposed to be stable while branches are intended to move. Maybe there's a technical reason they want you to use a moving tag?  ¯\\\_(ツ)\_/¯

**Comment by JohnMcLear** [comment]
@rhansen I modified your branch to ``use: saucelabs/sauce-connect-action@v1.1.2``

**Comment by christian-bromann** [comment]
@rhansen thanks for raising the issue. I pushed a v1 tag that represents the latest version. I believe the reason for this is to allow specifying the latest major version of an action. Now:

```js
use: saucelabs/sauce-connect-action@v1
```

should work. Please let me know if not.

**Comment by JohnMcLear** [comment]
I will bump and check once github actions is not broken ;\

**Comment by JohnMcLear** [comment]
Confirmed fixed: https://github.com/ether/etherpad-lite/runs/2004047095?check_suite_focus=true

**Comment by christian-bromann** [comment]
@JohnMcLear thanks for confirming. I looked at your account data and it seems you could use a bit more concurrency to run tests faster. Would you mind to give some credit to Sauce Labs in the readme? Something like:

```md
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-red.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)
```
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-red.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)
Maybe?

**Comment by JohnMcLear** [comment]
I'm not one to look a gift horse in the mouth but I do consider myself a shrewd negotiation and I'm keen to keep our color scheme so how about this instead..    

In a dream scenario there would be a sauce labs badge I could tie in..

Some reasons I'm pushing back a little despite this being a very awesome and generous offer.

1. Red in our Github page means failure / error.
2. The image provided is kinda pixelated and not in keeping with our other assets.

Thoughts?

**Comment by JohnMcLear** [comment]
Sorry I forgot to include this: https://github.com/ether/etherpad-lite/pull/4897 as an alternative...

**Comment by christian-bromann** [comment]
We can offer 3 color flavors:

```md
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-gray.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-red.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-white.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)
```
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-gray.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-red.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)
[![Testing Powered By SauceLabs](https://opensource.saucelabs.com/images/opensauce/powered-by-saucelabs-badge-white.png?sanitize=true "Testing Powered By SauceLabs")](https://saucelabs.com)

If you work with build names you can also use these badges:

```md
[![Sauce Test Status](https://saucelabs.com/browser-matrix/etherpad.svg?branch=master)](https://saucelabs.com/u/etherpad)
```
[![Sauce Test Status](https://saucelabs.com/browser-matrix/etherpad.svg)](https://saucelabs.com/u/etherpad)

or

```md
[![Sauce Test Status](https://saucelabs.com/buildstatus/etherpad.svg)](https://saucelabs.com/u/etherpad)
```
[![Sauce Test Status](https://saucelabs.com/buildstatus/etherpad.svg)](https://saucelabs.com/u/etherpad)

Any credit is appreciated. Thank you!

**Comment by JohnMcLear** [comment]
Oh wow I like those options, will look to see how we can implement "build names".

**Comment by JohnMcLear** [comment]
@christian-bromann merged initial with thanks. 

Our format for capabilities is somewhat different from the example showed in the build matrix, this is my attempt: https://github.com/ether/etherpad-lite/blob/50694630a42e55ca17032394a871728c6b5fdb37/src/tests/frontend/travis/remote_runner.js#L171

Will see what happens in test.

**Comment by JohnMcLear** [comment]
@christian-bromann is the matrix functioning as documented?  I noticed https://github.com/saucelabs-training/demo-sauce-status-badge shows all fails which seems unusual for a demo?

https://app.saucelabs.com/buildstatus/etherpad 

seems to work as does

https://app.saucelabs.com/buildstatus/etherpad?branch=saucelabs-props

but

https://app.saucelabs.com/buildstatus/etherpad?branch=wtfisgoingonthisbranchdoesntexist

shows complete despite no branch ever existing?

🐲 

https://app.saucelabs.com/buildstatus/nowaysuchaweird12345userSOLARWINDS123passwordexists

does however show unknown so some logic is happening.

**Comment by JohnMcLear** [comment]
``[![Sauce Test Status](https://app.saucelabs.com/buildstatus/etherpad.svg)](https://saucelabs.com/u/etherpad)``

[![Sauce Test Status](https://app.saucelabs.com/buildstatus/etherpad.svg)](https://saucelabs.com/u/etherpad) I think is the correct URL

**Comment by JohnMcLear** [comment]
@christian-bromann I went ahead and bumped the README again with another badge so hopefully the three references to Sauce Labs within our README brings you some customers through :)  It's worth noting that when I embed that badge using either the correct URL (as per my testing) or per the incorrect URL (as I placed in the README) then it fails..  So usually when direct access but indirect doesn't the CORS policy on the server is incorrect...  _But also it could be me doing something wrong again ;)_

I'd appreciate those extra tunnels, give me a shout when they are setup so I can test!  Thanks for the support ❤️

**Comment by christian-bromann** [comment]
> I went ahead and bumped the README again with another badge so hopefully the three references to Sauce Labs within our README brings you some customers through :)

Much appreciated 🙏 

> I'd appreciate those extra tunnels

What do you mean by that? I already bumped the account before our conversation. Is there anything else I can do for you?

**Comment by JohnMcLear** [comment]
Wow thanks no man that's great but you might want to report internally that I think the badges might need some attention...

**Comment by christian-bromann** [comment]
> you might want to report internally that I think the badges might need some attention...

I will take a look. Sauce badges work a bit different than CI/CD badges given that Sauce has no access to your code repository. It refers the data from your last run build which is why I suggested to have a build property in your capabilities. Also note that it is recommended to have one user/subaccount per project. If you use the same account for multiple projects the badge will not be able to differentiate.
