### ISSUE TITLE
Use the Sauce action without an access token

### ISSUE THREAD

**Issue by ChristophWurst** [saucelabs/sauce-connect-action#24]
Hi there,

I would like to suggest a feature: being able to use the sauce action in public repositories (true open source projects) but without having to specify an access token.

Right now the access key is required: https://github.com/saucelabs/sauce-connect-action#accesskey

For security best practice I might now want to put my access key into a public repository. The key isn't exposed by default when I put it into a *github secret*, but you anyone with write permission on the repo can change the workflow to print/send the key somewhere else. With the compromised key, someone could do harmful things.

Other integrations like Codecov work without an access token when used in a public repo: https://github.com/codecov/codecov-action#usage

Is there any technical possibility to allow CI builds from public repos to either not authenticate at all or authenticate as the *current github user* somehow?

I hope this makes sense, but let me know if you have any questions :)

Cheers

**Comment by christian-bromann** [comment]
Unfortunately this is not possible with Sauce Labs at the moment. Unlike CodeCov or other vendors where you can connect your public GitHub repository with the platform Sauce Labs always requires an username and access key. There are some internal conversations around how to deal with that moving on. I will keep you posted.

**Comment by ChristophWurst** [comment]
thanks a lot for the quick reply @christian-bromann.

I was afraid that there are technical barriers that have to be resolved. Is there any other mitigation strategy to lower the risk of what harm a stolen token could do? Something like a token that can only start tunnels would perhaps be an acceptable alternative.

**Comment by christian-bromann** [comment]
The best option I can think of so far is to create a specific sub account with a limited concurrency (e.g. not more than 2) dedicated to run tests for a specific repo. Then just hardcode the key in the public repo. Given the low ccy it is almost of no value to abuse this account.
