### ISSUE TITLE
Getting error "connect ECONNREFUSED"

### ISSUE THREAD

**Issue by Sandstedt** [saucelabs/sauce-connect-action#3]
Trying to use Github Action with Karma to connect to SouceLabs, but get's error while connecting to the browsers:

```
26 07 2020 12:45:25.991:INFO [karma-server]: Karma v5.1.0 server started at http://0.0.0.0:9876/
26 07 2020 12:45:25.994:INFO [launcher]: Launching browsers sl_chrome_latest with concurrency 5
26 07 2020 12:45:25.997:INFO [launcher]: Starting browser chrome on SauceLabs
26 07 2020 12:45:51.701:ERROR [SaucelabsLauncher]: { Error: connect ECONNREFUSED 127.0.0.1:33593
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:832:14)

  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 33593 }
```
(but it workes when running trough Travis CI)

See action running here: https://github.com/mojs/mojs/runs/911653366?check_suite_focus=true
Github Action: https://github.com/mojs/mojs/blob/github-actions/.github/workflows/ci.yml

**Comment by xavierfoucrier** [comment]
Ping @christian-bromann, thanks for your support :wink:

**Comment by xavierfoucrier** [comment]
Hi @christian-bromann @danmichaelo I think I found part of the issue.

- TravisCI: Sauce Connect 4.6.2, build 5183 ad61662, see [710657747](https://travis-ci.org/github/mojs/mojs/builds/710657747)
- Github Actions: Sauce Connect 4.5.4, build 4699 f256a9f, see [911653366](https://github.com/mojs/mojs/runs/911653366)

You should **update Sauce Connect** to the latest available version.

Again, big thanks for your feedback! :+1:

**Comment by christian-bromann** [comment]
Let's continue conversations in #6

**Comment by xavierfoucrier** [comment]
Hi @christian-bromann,

Thanks for the fix, I will give it a try and continue the conversation in #6.
:wink:

**Comment by xavierfoucrier** [comment]
Waiting to have the new version published on Github Actions to test. For now there is just the `v1.0.0` on the marketplace. Can you confirm @christian-bromann? Thanks! :wink:

**Comment by christian-bromann** [comment]
@xavierfoucrier yes, please see last comment in https://github.com/saucelabs/sauce-connect-action/issues/6#issuecomment-688473519. For now I advise to run from `master`.

**Comment by xavierfoucrier** [comment]
Ho! OK fine, I didn't saw this comment sorry. Can't wait to test it and see if it fix our problem. For now we have opened another ticket on the karma repository, but still no feedback from the team. Thanks for your fast answer :rocket: :wink:

**Comment by xavierfoucrier** [comment]
@christian-bromann OK unfortunately upgrading to `v1.1.0` doesn't fix this problem for us, we still have the issue here:
https://github.com/mojs/mojs/runs/1165335196?check_suite_focus=true#step:8:232

Probably this issue is not related to #6. :thinking:

**Comment by christian-bromann** [comment]
Try using `saucelabs/sauce-connect-action@v1.1.1`

**Comment by xavierfoucrier** [comment]
@christian-bromann same result :cry:
https://github.com/mojs/mojs/runs/1165972674?check_suite_focus=true#step:8:232

I guess everything works fine on your side because Sauce Connect is up and ready in the log...

**Comment by christian-bromann** [comment]
yeah, not sure what the difference is here

**Comment by xavierfoucrier** [comment]
@christian-bromann exactly the same result... will try something different. Thanks again for your time :wink:
