### ISSUE TITLE
Update `save-state` command to use new environment file

### ISSUE THREAD

**Issue by GraemeWatt** [saucelabs/sauce-connect-action#61]
Using `saucelabs/sauce-connect-action@v2` I get a warning message ([example run](https://github.com/HEPData/hepdata/actions/runs/3625751237)):

> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The warnings will turn to errors starting 1st June 2023.  Could you please make the changes described in the GitHub blog post?

**Comment by GraemeWatt** [comment]
Thanks for addressing this issue.  Could you please move the major version tag `v2` as recommended in the [GitHub Docs](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)?  Currently it points to `v2.3.2` from 26th January 2023 and so it's missing the updates from `v2.3.3` and `v2.3.4`.

**Comment by waggledans** [comment]
Done
