### ISSUE TITLE
How to specify log file location via parameter?

### ISSUE THREAD

**Issue by dragos-panzaru-md** [saucelabs/sauce-connect-action#78]
I looked through the documentation, but I can not see how to specify a custom location for the the tunnel logfile, when using sauce-connect-action.

**Comment by waggledans** [comment]
We didn't see a reason to allow a custom location since SC runs in a container (and you don't have access to its file system). You can access the log file following the instructions in README:
https://github.com/saucelabs/sauce-connect-action#sauce-connect-proxy-log
