### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by anselmbradford** [saucelabs/sauce-connect-action#86]
<img width="1135" alt="Screenshot 2024-02-09 at 12 26 03 PM" src="https://github.com/saucelabs/sauce-connect-action/assets/704760/121cc5ed-057e-4446-a7d1-0be1a2b24ddc">

**Comment by djbrown** [comment]
thank you @waggledans for fixing and @mmatczuk for releasing ❤🚀
